### ISSUE TITLE
Add filebrowser image

### ISSUE THREAD

**Issue by rgaudin** [offspot/container-images#2]
<img width="1033" alt="apps" src="https://user-images.githubusercontent.com/57929/195319034-2b8befee-ad9c-407e-a51c-bfcbeb08ea75.png">

For `Nomad`, `Math Mathews`, `Africatik` and more to come (according to @Popolechien), we need a generic app that serves static files with or without an index page.

This would be nicely done using a caddy image configured with [`file_server`](https://caddyserver.com/docs/modules/http.handlers.file_server).

In an initial version, as all packages have a support webpage, that would be enough.

Later, we could invest some time to tweak the template so it's better integrated and/or more practical.

**Comment by kelson42** [comment]
Might be possible to make the ZIM files available for download via this?
