### ISSUE TITLE
Add captive-portal image

### ISSUE THREAD

**Issue by rgaudin** [offspot/container-images#3]
We need an image that replicates the hostpost's captive portal, interacting with the host's firewall and redirecting to the appropriate homepage.

**Comment by kelson42** [comment]
IMO, would be good to have a dedicated repository for the code itself of the captive portal.

**Comment by rgaudin** [comment]
I agree this is probably best if we want to foster its integration into other's system. That said it may be additional work so we might do it in stages.

**Comment by kelson42** [comment]
@rgaudin Supportive of investigating the time soon.

**Comment by Popolechien** [comment]
We can keep it all.

**Comment by rgaudin** [comment]
Fixed in a696781
