### ISSUE TITLE
Should we restore the HTTPs tutorial?

### ISSUE THREAD

**Issue by rgaudin** [offspot/container-images#47]
In Kiwix-hotspot, we had an [HTTPs Tutorial](https://github.com/offspot/kiwix-hotspot/tree/0f3195e9aa60ec9ee930e4a30be3c16b057c7538/ansiblecube/roles/home/files/https-tutorial) that was a static HTML page with GIF animations depicting how to bypass the various warnings in order to access content via HTTPs.

![Capture d’écran 2021-07-27 à 10 06 07](https://user-images.githubusercontent.com/21675885/127119561-f2afd5d0-4634-43dd-87c0-43af2745ad0a.png)

This was displayed when accessing via HTTP a ZIM which had the `_sw:yes` tag. The goal of this was to ease the use of zimit1 ZIMs.

This feature has not been implemented in the dashboard. In the light of the zimit2 release coming, **should we back port the feature or not?** @kelson42 @Popolechien 

Bear in mind that those animations must be redone (obsolete) and that Chrome cannot be bypassed anynore (see https://github.com/offspot/kiwix-hotspot/issues/608)

**Comment by Popolechien** [comment]
What's our current timeline for the release of zimit2? A month or so? 

We currently get 20-ish new images out every month, so probably not worth spending time/resources on it (as opposite to answering emails of people coming to complain).
