### ISSUE TITLE
Add timesetting image

### ISSUE THREAD

**Issue by rgaudin** [offspot/container-images#5]
We need to replicate [`time.<name>.offspot`](https://github.com/offspot/kiwix-hotspot/wiki/Keeping-Time) service from hostspot: allowing time and date setting **on the host**, either permanently (if device has a clock module) or temporarily.

**Comment by kelson42** [comment]
I guess we need it to provide future images for Wikifundi RPIs. @Anthere How does looks like the future versions? Do you will need a refreshment? With new languages supported?

**Comment by Anthere** [comment]
We do not have plans at the moment for a new version or new languages.... thanks

**Comment by kelson42** [comment]
Not sure this should be made in a dedicated image. Actually I don't really see any advantage to do so. To me this is part of the admin dashboard. As such, I would propose to move `offspot/dashboard` (and code should be migrated & adapted from `offspot/kiwix-hotspot`.

**Comment by rgaudin** [comment]
The dashboard has no ETA while we need this feature for the initial release. We can still merge that into the dashboard later on.

**Comment by kelson42** [comment]
OK, personnaly, regarding the feedback of @Anthere I will be OK to got for in in `1.1.0` or `1.2.0`. I can leave with such a feature regression for a few months, in particular because there is no pressure on user side.

**Comment by rgaudin** [comment]
Your call but we'd have to remove WF from the cardshop to be consistent

**Comment by Anthere** [comment]
Errr, the removal from the cardsharp would not be great :(
