### ISSUE TITLE
Don't display Kiwix-readers header in Downloads if none

### ISSUE THREAD

**Issue by rgaudin** [offspot/container-images#50]
When user did not select to include Kiwix-readers (ie. when the `readers` is empty/missing), we should not display the Kiwix readers banner on top of downloads

dashboard-1.4+

**Comment by kelson42** [comment]
@rgaudin Would that not be wise to have a dedicated dashboard repo?

**Comment by rgaudin** [comment]
> @rgaudin Would that not be wise to have a dedicated dashboard repo?

Can we discuss a general policy (with @benoit74) about this? It feels like going back and forth and without a policy it's neither the standard nor the exception, which makes it annoying.
