### ISSUE TITLE
Add KA-lite image ?

### ISSUE THREAD

**Issue by rgaudin** [offspot/container-images#6]
Aflatoun and Khan-Academy apps relied on an obsolete piece of python software named KA-Lite.

We are transitioning the very popular KHAN-Academy apps to ZIM files.

Aflatoun being a static (ka-lite-specific) dump of non-available-online content, we should discuss whether this content is important-enough to justify investing time in supporting it.

Supporting it could either be creating an image for the current code, or finding out if updated content exists and can be scraped or scraping content off a ka-lite setup. The former being the easiest probably.

@Popolechien do we have data on Aflatoun usage and its usefulness within our user base? Because of its “interactive” label, it's highlighted in the cardshop and thus frequently included but that is biased.

**Comment by Popolechien** [comment]
@rgaudin Orange confirmed we can get rid of Aflatoun. They're the only institutional I'm aware of that uses it.

**Comment by rgaudin** [comment]
Good news, then we won't port KA-Lite.
