### ISSUE TITLE
Why not using directly Kiwix Serve official container image?

### ISSUE THREAD

**Issue by kelson42** [offspot/container-images#62]
Available at https://github.com/kiwix/kiwix-tools/pkgs/container/kiwix-serve

**Comment by rgaudin** [comment]
You and I decided that offspot should use dedicated containers to ensure quality (fit/adapted, no risk of unexpected change).

Also kiwix images used to have different platform support (now it's aligned)

Also, not imposing/monitoring contraints on other projects is a relief.

Also, kiwix-serve image uses an entrypoint that we don't want.

I find maintaining this image painless but if you want to remove it, keeping kiwix-tools image (with the other tools inside) would be better/simpler than kiwix-serve image IMO

**Comment by kelson42** [comment]
Thanks, it's clear, closing the ticket then.
